### PR TITLE
Happy to learn python every day

### PR DESCRIPTION
**Pull request by Cuiyansong**

### CODE REVIEW

**Comment by Cuiyansong** [comment]
Sorry, this is a wrong pull request, I want to pull this pr in my repro, but here.

Anyway, you did a good work, I study a lot on it~~~Tkx

**Comment by qiwsir** [comment]
没关系。这个教程中还有一些错误，等待修改；也有一些地方讲述的不是很好，不适合初学者学习。请多指点。

2015-12-08 22:29 GMT+08:00 Stephen Cui <notifications@github.com>:

> Closed #37 <https://github.com/qiwsir/StarterLearningPython/pull/37>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qiwsir/StarterLearningPython/pull/37#event-485692955>.
>



-- 
*QiWei*

**Comment by Cuiyansong** [comment]
我看到有些PR就是修改个别错别字的，为什么不merge进来呢？

**Comment by qiwsir** [comment]
有的修改了。已经merge，但是，不知道为什么，有的merge操作找不到。哈哈。有空好好找找。谢谢提示。

**Pull request closed without merging**
